Frontend/proxima/Proxima/Controllers/ProjectController.cs
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Proxima.Models;

namespace Proxima.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;
        private readonly ApplicationDbContext _context;
        public ProjectController(IConfiguration configuration,ApplicationDbContext context)
        {
            _configuration = configuration;
            _httpClient = new HttpClient
            {
                BaseAddress = new System.Uri(_configuration["WebApiBaseUrl"])
            };
            _context = context;
        }

        public async Task<IActionResult> ProjectList()
        {

            //var response = await _httpClient.GetAsync("api/Project");
            //if (response.IsSuccessStatusCode)
            //{
            //    var data = await response.Content.ReadAsStringAsync();
            //    var projects = JsonConvert.DeserializeObject<List<ProjectModel>>(data);
            //    return View(projects);
            //}
            //return View(new List<ProjectModel>());
            var projects = await _context.Projects.ToListAsync();
            return View(projects);
        }

        [HttpPost]
        public async Task<JsonResult> SaveProject([FromBody] ProjectSave project)
        {
            HttpResponseMessage response;
            
            if (project.ProjectID > 0)
            {
                var jsonContent = JsonConvert.SerializeObject(project);
                var content = new StringContent(jsonContent , Encoding.UTF8, "application/json");
                response = await _httpClient.PutAsync($"api/Project/{project.ProjectID}", content);
            }
            else
            {
                var jsonContent = JsonConvert.SerializeObject(project);
                var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");
                response = await _httpClient.PostAsync($"api/Project", content);
            }
            return Json(response.IsSuccessStatusCode);
        }

        public async Task<ActionResult> ProjectDetails(int id)
        {
            var projectResponse = await _httpClient.GetAsync($"api/Project/{id}");
            var taskResponse = await _httpClient.GetAsync($"api/Task/TasksByProjectID/{id}");
            var milestoneResponse = await _httpClient.GetAsync($"api/Milestone/MilestonesByProjectID/{id}");
            var response = await _httpClient.GetAsync($"api/ProjectAttachment/AttachmentByProjectID/{id}");

            var viewModel = new ProjectDetailsViewModel();
            if (projectResponse.IsSuccessStatusCode)
            {
                string projectData = await projectResponse.Content.ReadAsStringAsync();
                viewModel.Project = JsonConvert.DeserializeObject<ProjectModel>(projectData);
            }
            if (taskResponse.IsSuccessStatusCode)
                {
                    string taskData = await taskResponse.Content.ReadAsStringAsync();
                    viewModel.Tasks = JsonConvert.DeserializeObject<List<TaskModel>>(taskData);
                }
            if (milestoneResponse.IsSuccessStatusCode)
            {
                string milestoneData = await milestoneResponse.Content.ReadAsStringAsync();
                viewModel.Milestones = JsonConvert.DeserializeObject<List<MilestoneModel>>(milestoneData);
            }
            if(response.IsSuccessStatusCode)
            {
                string attachmentData = await response.Content.ReadAsStringAsync();
                viewModel.Attachments = JsonConvert.DeserializeObject<List<ProjectAttachmentModel>>(attachmentData);
            }
            return View(viewModel);
        }

        public async Task<ActionResult>  ProjectOverview(int id)
        {
            var response = await _httpClient.GetAsync($"api/Project/{id}");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                var project = JsonConvert.DeserializeObject<ProjectModel>(data);
                return PartialView("_ProjectOverview", project);
            }
            return PartialView("_ProjectOverview",new ProjectModel());
        }
        public async Task<ActionResult> ProjectTasks(int id)
        {
            var response = await _httpClient.GetAsync($"api/Task/TasksByProjectID/{id}");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                var tasks = JsonConvert.DeserializeObject<List<TaskModel>>(data);
                return PartialView("_ProjectTasks", tasks); 
            }
            return PartialView("_ProjectTasks", new List<TaskModel>());
        }

        public async Task<ActionResult> ProjectMilestones(int id)
        {
            var response = await _httpClient.GetAsync($"api/Milestones/MilestonesByProjectID/{id}");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                var milestones = JsonConvert.DeserializeObject<List<MilestoneModel>>(data);
                return PartialView("_ProjectMilestones", milestones);
            }
            return PartialView("_ProjectMilestones", new List<MilestoneModel>());
        }

        public IActionResult TaskDetails()
        {
            return View();
        }

        public async Task<IActionResult> ProjectFiles(int id)
        {
            var response = await _httpClient.GetAsync($"api/ProjectAttachment/AttachmentByProjectID/{id}");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                var files = JsonConvert.DeserializeObject<List<ProjectAttachmentModel>>(data);
                return PartialView("_ProjectFiles", files);
            }
            return PartialView("_ProjectFiles", new List<ProjectAttachmentModel>());
        }

        //public IActionResult ProjectFiles()
        //{
        //    return PartialView("_ProjectFiles");
        //}

    }
}

Frontend/proxima/Proxima/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Proxima.Models;

namespace Proxima.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;
        private readonly ApplicationDbContext _context;
        public TaskController(IConfiguration configuration, ApplicationDbContext context)
        {
            _configuration = configuration;
            _httpClient = new HttpClient
            {
                BaseAddress = new System.Uri(_configuration["WebApiBaseUrl"])
            };
            _context = context;
        }

        public async Task<ActionResult> TaskDetails(int id)
        {
            // Check if taskId is coming through
            Console.WriteLine($"Task ID: {id}");  // This will print to the server log

            var response = await _httpClient.GetAsync($"api/Task/{id}");
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                var task = JsonConvert.DeserializeObject<TaskModel>(data);
                return View(task);
            }
            return View(new TaskModel());
        }

        [Authorize]
        public async Task<ActionResult> MyTasks()
        {
            var userId = User.FindFirst("UserID")?.Value;
            var response = await _httpClient.GetAsync($"api/Task/TasksByUserID/{userId}");

            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                var tasks = JsonConvert.DeserializeObject<List<TaskModel>>(data); // Deserialize into List<TaskModel>
                return View(tasks);
            }

            return View(new List<TaskModel>()); // Return an empty list if API fails
        }


    }
}

Frontend/proxima/Proxima/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Proxima.Models;

namespace Proxima.Controllers
{
    public class UserController : Controller
    {

        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;
        public UserController(IConfiguration configuration)
        {
            _configuration = configuration;
            _httpClient = new HttpClient
            {
                BaseAddress = new System.Uri(_configuration["WebApiBaseUrl"])
            };
        }
        public IActionResult UserList()
        {
            return View();
        }
    }
}

Frontend/proxima/Proxima/Views/Shared/_Layout.cshtml
@inject Proxima.CommonVariable commonVariable
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ProManage</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/vendors/font-awesome/css/font-awesome.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/assets/vendors/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="~/assets//css//kanban.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.6.6/dragula.min.css" integrity="sha512-49xW99xceMN8dDoWaoCaXvuVMjnUctHv/jOlZxzFSMJYhqDZmSF/UnM6pLJjQu0YEBLSdO1DP0er6rUdm8/VqA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style1.css">
    <link rel="stylesheet" href="~/assets/css/style2.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center">
                @* <span class="mdi mdi-vector-link text-primary" style="font-size:1.5rem;"></span>
                <a class="text-primary text-decoration-none"><h3>ProManage</h3></a> *@
                <a style="font-size:1.5rem;font-weight:600" class="h1 page-title navbar-brand brand-logo mx-auto text-primary" asp-controller="Home" asp-action="Index">
                    <span class="">
                        <i class="mdi mdi-vector-link"></i>
                    </span> ProManage
                </a>
                @* <a class="navbar-brand brand-logo" href="index.html"><img src="~/assets/images/logo.svg" alt="logo" /></a> *@
                @* <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/assets/images/logo-mini.svg" alt="logo" /></a> *@
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-stretch">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="mdi mdi-menu"></span>
                </button>
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="nav-profile-img">
                                <img src="~/assets/images/faces/face1.jpg" alt="image">
                                <span class="availability-status online"></span>
                            </div>
                            <div class="nav-profile-text">
                                <p class="mb-1 text-black">@commonVariable.GetUserName()</p>
                            </div>
                        </a>
                        <div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
                            @* <a class="dropdown-item" href="#">
                                <i class="mdi mdi-cached me-2 text-success"></i> Activity Log
                            </a> *@
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">
                                <i class="mdi mdi-logout me-2 text-primary"></i> Signout
                            </a>
                        </div>
                    </li>

                    <li class="nav-item d-none d-lg-block full-screen-link">
                        <a class="nav-link">
                            <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
                        </a>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                    <span class="mdi mdi-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a href="#" class="nav-link">
                            <div class="nav-profile-image">
                                <img src="~/assets/images/faces/face1.jpg" alt="profile" />
                                <span class="login-status online"></span>
                                <!--change to offline or busy as needed-->
                            </div>
                            <div class="nav-profile-text d-flex flex-column">
                                <span class="font-weight-bold mb-2">@commonVariable.GetUserName()</span>
                                <span class="text-secondary text-small">@commonVariable.GetUserRole()</span>
                            </div>
                            <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                <span class="menu-title">Dashboard</span>
                                <i class="mdi mdi-home menu-icon"></i>
                            </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Project" asp-action="ProjectList">
                            <span class="menu-title">Projects</span>
                            <i class="mdi mdi-folder-file menu-icon"></i>
                        </a>
                    </li>
                    @if (User.IsInRole("Project Manager") || User.IsInRole("Team Member") || User.IsInRole("Client"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Task" asp-action="MyTasks">
                                <span class="menu-title">My Tasks</span>
                                <i class="mdi mdi-list-box-outline menu-icon"></i>
                            </a>

                        </li>
                    }
                    @if(User.IsInRole("Admin")){
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="User" asp-action="UserList">
                                <span class="menu-title">Users</span>
                                <i class="mdi mdi-account-multiple menu-icon"></i>
                            </a>

                        </li>
                    }
                    
                    
                </ul>
            </nav>
            <div class="main-panel">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
                <!-- partial:partials/_footer.html -->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2023 <a href="https://www.bootstrapdash.com/" target="_blank">BootstrapDash</a>. All rights reserved.</span>
                        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
                    </div>
                </footer>
                <!-- partial -->
            </div>
        </div>
    </div>
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/assets/vendors/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <script src="~/assets/js/jquery.cookie.js"></script>
    <script src="~/assets/js/task.js"></script>
    <script src="~/assets/js/kanban.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dragula/3.6.6/dragula.min.js" integrity="sha512-MrA7WH8h42LMq8GWxQGmWjrtalBjrfIzCQ+i2EZA26cZ7OBiBd/Uct5S3NP9IBqKx5b+MMNH1PhzTsk6J9nPQQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/assets/js/dashboard.js"></script>
    <!-- End custom js for this page -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Frontend/proxima/Proxima/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/vendors/font-awesome/css/font-awesome.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style1.css">
    <link rel="stylesheet" href="~/assets/css/style2.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
</head>
<body>
    @RenderBody()
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <script src="~/assets/js/jquery.cookie.js"></script>
    <!-- endinject -->
</body>
</html>

Frontend/proxima/Proxima/Views/Shared/_Layout_Register.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/vendors/font-awesome/css/font-awesome.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style1.css">
    <link rel="stylesheet" href="~/assets/css/style2.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
</head>
<body>
    @RenderBody()
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <script src="~/assets/js/jquery.cookie.js"></script>
    <!-- endinject -->
</body>
</html>